name: 👀 Bug report
description: Create a report to help us improve
title: "[Bug]: "

body:
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
      placeholder: My Proxmox connection isn't working; I get an infinite loading screen when I try to connect.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Open the app
        2. Add a server
        3. See error...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: The connection to my Proxmox server should work and there should be no infinite loading.
    validations:
      required: true

  - type: input
    attributes:
      label: Device
      description: On which device did you encounter this bug?
      placeholder: MacBook Pro M2
    validations:
      required: true

  - type: input
    attributes:
      label: macOS Version
      description: On which macOS version did you encounter this bug?
      placeholder: macOS 15.0
    validations:
      required: true

  - type: input
    attributes:
      label: ProxmoxBar Version
      description: Which version are you using? (displayed in Settings)
      placeholder: "1.0.7"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots / Link to video
      description: If applicable, add screenshots or a link to a video to help explain your problem.
      placeholder: Click on the 📎 icon to import a photo/video
    validations:
      required: false