name: ✨ Feature request
description: Suggest an idea for this project
title: "[Feature]: "

body:
  - type: textarea
    attributes:
      label: Feature description
      description: A clear and concise description of what the feature is.
      placeholder: I would like to be able to sort VMs by RAM usage.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation / Use Case
      description: Why is this feature needed? What problem does it solve?
      placeholder: Currently, it's hard to find which VM is consuming the most resources when I have many running.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe how you imagine the feature working.
      placeholder: Add a sort button in the header or a dropdown to select "Sort by Memory".
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: Have you considered other ways to solve this?
      placeholder: I defined a naming convention to sort them alphabetically, but it's not dynamic enough.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots / Mockups
      description: If applicable, add screenshots or mockups to help explain your idea.
      placeholder: Click on the 📎 icon to import a photo/video
    validations:
      required: false
